### PR TITLE
JUnit test codes for storage [PANDORA BOX]

### PR DESCRIPTION
**Pull request by Kair0s3**
JUnit test for storage class by working on a specific test recipe file and excluding out files already existing (anything that is not the test recipe on the tester's recipe folder.

### CODE REVIEW

**Comment by Kair0s3** [comment]
Will fix this later after DG finish up

**Comment by Kair0s3** [comment]
Update - I have no idea why is the test not working, locally it is working fine
image

*Note that the error message appearing is normal since, my current recipe directory has some existing invalid files alr - but it should not affect the JUnit since the target file in the JUnit test is `testfile1.txt`. What is more weird from my point of view is the null pointer exception at `line:123` suggesting that maybe gradle test is unable list the files (on `line:120`) hence, that line where it is retrieving all files in the `recipe` directory fails and returns null instead.

Below is an image for reference

image

**Comment by Kair0s3** [comment]
Fix for the previous issue, was that if the recipe directory yet to exist, then the list file method results in null and hence, null pointer. So the fix is to have a BeforeAll, AfterAll to check if it exist in the first place, then restore the original state (eg. if no recipe directory initially, then remove the created recipe directory after all test)

**Review by arraysius — APPROVED** [review]
LGTM

**Review by rizemon — APPROVED** [review]
LGTM

**Pull request merged**
